### ISSUE TITLE
Production Type

### ISSUE THREAD

**Issue by mkm1879** [AAVLD-USAHA-ITStandards/eCVI#10]
On the 2/8/18 call the Production Type issue was raised again.  This is not currently a distinct field in the standard but is sometimes touched on by Species or Purpose of Movement.  The issue is complicated by the fact that "Dairy" and "Beef" cattle are defined in the ADT rule by breed rather than use.

**Comment by KimberlyTsao-USDA** [comment]
Some concerns about explicitly including production type (whether in its own field or not) are:

- It's not particularly meaningful to standardize across commodity groups (i.e. dairy vs broilers vs finishers).  As the variety of animals for which this is used grows, this seems especially vulnerable to maintenance issues.
- Even within commodity groups, the varying definitions (as with the Dairy/Beef example) introduces a real risk that data entered that says the same thing doesn't mean the same thing, substantially decreasing the value of the information.

These concerns may be overridden by the usefulness of specifying a production type to answer certain questions, but what are those questions?

**Comment by mkm1879** [comment]
This should be drawing more discussion than it is (IMHO).  Leave open for now.  A value-set will need to be agreed upon quickly if we implement.

**Comment by jwilcke** [comment]
The problem you face is that values in a "production type" field are context dependent.   An "applicable" and understandable list depends on the species of record.  In this case, a value entered in the species field creates the context of the record in this regard.  I can think of two solutions.  One I hate as a terminologist, the other adds complexity nobody wants to deal with (including me).

1. You can embed the context in the value-set.  Every production class would include the name of the species (e.g. broiler chicken rather than just broiler).
2. You can create multiple value sets and somehow trigger them when the context is created.  It would still be best to tie the production classes to something that creates obvious understanding.  In SNOMED that's the "fully specified name" (about which I have less and less faith all the time) or truly human readable definitions.

Either way, the "solution" rapidly becomes intractable and I fear that neither would produce a good benefit / difficulty ratio.   Oh, and I can't fix the problem that Holstein heifer steaks are tasty.  ;-)

-Jeff

**Comment by mkm1879** [comment]
Leaving these as one "Purpose of Movement" element with the best list we can come up with.  Understanding that this is far less than perfect but meets 90% of regulatory needs.
