### ISSUE TITLE
Electronic signature standards

### ISSUE THREAD

**Issue by Deevet84** [AAVLD-USAHA-ITStandards/eCVI#17]
Has this group addressed any standards or accepted ways to have the e-signature attached to a cvi and be accepted as valid?

 Dee Ellis
TAMU

**Comment by mkm1879** [comment]
Because this standard is for exchange of data from an eCVI rather than for the eCVI itself, the committee ruled electronic signature out of scope.  The attachment mechanism can be used to attach a signed document—such as what my Civet program does with signed CO/KS eCVI—or to carry other evidence of eSignature outside the scope of the standardization.

Michael K. Martin, DVM, MPH, DACVPM
Clemson Livestock Poultry Health
PO Box 102406
Columbia, SC 29224-2406
email: mmarti5@clemson.edu<mailto:mmarti5@clemson.edu>
direct line: (803) 726-7808
cell: (803)312-1439

The greatest enemy of knowledge is not ignorance,
it is the illusion of knowledge.
STEPHEN HAWKING

**Comment by mkm1879** [comment]
Will close soon, if no further discussion.

**Comment by mkm1879** [comment]
Closing.  Out of scope.
