### ISSUE TITLE
Accreditation Number Required?

### ISSUE THREAD

**Issue by mkm1879** [AAVLD-USAHA-ITStandards/eCVI#27]
It has been suggested that the National Accreditation Number should be required rather than optional.  This is legally required for all vets writing CVIs and should be available to any eCVI applications.  Any objections to this last minute change?

**Comment by mkm1879** [comment]
I almost forgot to represent myself here.  I have to cast a "no" vote on this one.  My use case is transcription of paper CVIs forwarded from the origin state without the accreditation number on the form.  We definitely want to import these but we have no access to the NAN.

**Comment by mkm1879** [comment]
This has been re-raised by the National Assembly of State Animal Health Authorities.  It doesn't seem that this is a big problem for "real" eCVIs.  So I withdraw my negative and ask this be reopened.

**Comment by ryanscholzdvm** [comment]
@mkm1879, I think that I would tend to agree with your original dissenting opinion for the same reason. We also convert paper CVIs into an eCVI format and provide an XML file along with the PDF, which while it may not necessarily be complete, it does validate currently. If this field is required, it may make it difficult in some cases to do this, and would likely limit future implementations that attempt to do this. I would propose this may be better fit as a policy decision for the NASAHO eCVI approval committee's standard for "real" eCVIs, rather than include this requirement in the data standards itself.

**Comment by StaceySchwabenlander** [comment]
I'm unsure of where the right place for this is, but I fully support that the NAN should be a required field. Whether that is through the XML schema here or through NASAHO's eCVI standards subcommittee.

**Comment by rmunger** [comment]
I agree the NAN should be a required field, but this requirement should not be enforced in the XML schema.

We are requiring a NAN in the Animal Health Services (AHS) eCVI app and also use it to as a component of the certificate number.

Randy D. Munger, DVM
Mobile Information and Animal Disease Traceability
USDA APHIS VS Strategy & Policy
Center For Informatics
2150 Centre Ave. Bldg. B Mail Stop 2E6
Fort Collins, CO 80526
Office 970-494-7339
Mobile 970-217-1432

**Comment by SusanCulpDVM** [comment]
@mkm1879 related to #58?

**Comment by SusanCulpDVM** [comment]
This issue was discussed at the November 30, 2022 meeting of the eCVI Data Standards Workgroup.  Since this is outside of the scope of this Workgroup, the consensus was to close this issue and refer it to the NASAHO eCVI Approval Committee.
