### ISSUE TITLE
GroupLot inspection date

### ISSUE THREAD

**Issue by mkm1879** [AAVLD-USAHA-ITStandards/eCVI#28]
Was it just an oversight that Animal includes inspection date, while GroupLot does not?  Or did we decide it was safe to assume issue date = inspection date for a group?

**Comment by StaceySchwabenlander** [comment]
We can not assume that the issue date = the inspection date. As an example, if veterinarians are issuing CVIs for swine with GroupLot ID, swine veterinarians may have a regular health maintenance program [as defined by 9CFR1, 160.1, 161.4(a)] which would typically mean the issue date does not = the inspection date, since CVIs can be issued up to 30 days from inspection. 

I think it would be important to make sure SAHOs know both the issue date as well as the inspection date for each CVI, whether the CVI is for individual animals or group/lot.

**Comment by mmcgrath** [comment]
see https://github.com/AAVLD-USAHA-ITStandards/eCVI/commit/577f1f5bb9c929626ef0b2cfda6939d404bcca24 for the proposed implementation by @mkm1879

**Comment by mkm1879** [comment]
Optional or required?

**Comment by StaceySchwabenlander** [comment]
I vote for required - both fields. 
-A CVI is valid for 30 days from inspection date, which makes this field required so we can all verify the CVI is valid.
-A CVI must be issued within 10 days (the norm) or 30 days (reg health main program) from inspection date, which makes both of these fields required to verify the CVI is being issued within legal timelines.

**Comment by SusanCulp** [comment]
@mkm1879, should you remove the Policy label on this since it is currently in the list of possible commits?

**Comment by jconlon** [comment]
What about @StaceySchwabenlander vote for this being required?

**Comment by StaceySchwabenlander** [comment]
Apologies @jconlon - I am just seeing this now. Yes. I vote for both the inspection date and the issue date to be required as I outlined above. Thank you!

**Comment by mkm1879** [comment]
In Jan 2021 release v2.3
