### ISSUE TITLE
Case Sensitivity

### ISSUE THREAD

**Issue by mkm1879** [AAVLD-USAHA-ITStandards/eCVI#71]
Our patterns for Animal IDs are currently case-sensitive.  NUES tags, for example, allow only upper case letters.  Should these be case insensitive?  Have seen this error from some new implementations.  Not hard for them to work through, but is it necessary?

**Comment by jconlon** [comment]
Are you asking if our Animal IDs patterns should be loosened to ignore case and be case insensitive?

**Comment by mkm1879** [comment]
Yes, that is the question.

**Comment by SusanCulpDVM** [comment]
@mkm1879 this was a problem for both mCVI and the mCVI replacement product in that neither product when launched required case-sensitivity.  My understanding was it was fairly easy to work through to correct so that they validated.  I don't feel like Animal ID patterns should be loosened if the pattern currently for Animal IDs are currently case-sensitive.

**Comment by StaceySchwabenlander** [comment]
Agree. NUES tags are all upper case and regular expressions can be written to validate that this is the case. I think the consistency of always making sure the NUES tags are upper case is important and easier for all.

**Comment by mkm1879** [comment]
Closed by consensus.
