### ISSUE TITLE
Official ID Types

### ISSUE THREAD

**Issue by SusanCulpDVM** [AAVLD-USAHA-ITStandards/eCVI#77]
Comment at Wednesday, August 31, 2022 eCVI Data Standards Workgroup meeting that there is confusion about Official ID (and Other ID) in the schema.  Request for eCVI Data Standards Workgroup to re-evaluate what is listed in the schema to determine if changes may be indicated.

**Comment by SusanCulpDVM** [comment]
https://github.com/AAVLD-USAHA-ITStandards/eCVI/blob/96ad415de93bcd4c124e53fdf8ebe4b204765daa/ecvi2.xsd#L869-L960

**Comment by rmunger** [comment]
I'm not sure why for manufacturer encoded rfid 900 is excluded but 999 appears to be allowed. If you look at the ICAR website you will find the 900 prefix is shared by multiple manufacturers (each assigned a series of numbers within 900) and can be tracked as any other manufacturer encoded devices. The more concerning issue is the apparent allowance of 999 prefixed tags which is a reserved series for testing and experimental usage by anyone, these are even found on collars used at some dairies to track milk production and are reused on different animals. A 999 prefixed tag is the equivalent to a management ID without any assurance of uniqueness.

> RFID devices for Conformance certification: Ear tags / Tag attachments / Boluses | ICAR<https://www.icar.org/index.php/rfid-tags/>


My other concern is that allowing 840, 124 and 484 prefixed IDs make perfect sense for cattle/bison but what about horses? It is my experience that horses entering the US have many different country coded implants (Spain, Netherlands, Germany...). Is there any thought or discussion on how to support a much wider variety of prefixes where necessary?

Randy D. Munger, DVM
Mobile Information
USDA APHIS VS Strategy & Policy
Center For Informatics
2150 Centre Ave. Bldg. B Mail Stop 2E6
Fort Collins, CO 80526
Office 970-494-7339
Mobile 970-217-1432

From: SusanCulpDVM ***@***.***>
Sent: Tuesday, September 6, 2022 9:14 AM
To: AAVLD-USAHA-ITStandards/eCVI ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [AAVLD-USAHA-ITStandards/eCVI] Official ID Types (Issue #77)


Comment at Wednesday, August 31, 2022 eCVI Data Standards Workgroup meeting that there is confusion about Official ID (and Other ID) in the schema. Request for eCVI Data Standards Workgroup to re-evaluate what is listed in the schema to determine if changes may be indicated.

-
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAAVLD-USAHA-ITStandards%2FeCVI%2Fissues%2F77&data=05%7C01%7C%7C02ad5ddbbcba4e3983ab08da901a6183%7Ced5b36e701ee4ebc867ee03cfa0d4697%7C0%7C0%7C637980740217890123%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=N2jM1FENLHLVNejpjHJMh3Ya1uvRCSksTGZi2TdCr0M%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHKG6FITHTMOTRDVOSJPTN3V45NSHANCNFSM6AAAAAAQF5WW4E&data=05%7C01%7C%7C02ad5ddbbcba4e3983ab08da901a6183%7Ced5b36e701ee4ebc867ee03cfa0d4697%7C0%7C0%7C637980740217890123%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=D6R58DTNJQWao5L%2BHo9wlp1O522EK5IAoSeSXCJGfEQ%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.******@***.***>>




This electronic message contains information generated by the USDA solely for the intended recipients. Any unauthorized interception of this message or the use or disclosure of the information it contains may violate the law and subject the violator to civil or criminal penalties. If you believe you have received this message in error, please notify the sender and delete the email immediately.

**Comment by ryanscholzdvm** [comment]
@rmunger, I think that there may be a misprint in the documentation for the MfrRFID. If you continue down further to the MfrRFIDType (where the reges is included), it actually does enforce exactly what you are suggesting- it allows 900-998.

I would propose that we correct the documentation to reflect that it allows 900 series prefixes, excluding 999.

For the other portion of your comment regarding other state prefixes, I remember the discussion where these prefixes were included (I'll have to go back and see if I can find the issue), and I remember the decision being made to include them here rather than as an AIN, but I don't remember why only the two prefixes were added. I suppose it is probably similar to the issue of the state codes on NUES tags and we just need to expand the RegEx to include all of the possibilities. It looks like the list you provided includes all of the 900 series assignments, but do you have a link to the list of the country code prefixes (I'm assuming it is probably in the ISO standard?)

**Comment by ryanscholzdvm** [comment]
A second link that includes the tag type list for other official ID, and the RegEx for the defined official ID types is:

https://github.com/AAVLD-USAHA-ITStandards/eCVI/blob/96ad415de93bcd4c124e53fdf8ebe4b204765daa/ecvi2.xsd#L1043-L1152

**Comment by mkm1879** [comment]
These regular expressions can be very hard to read, even for those who know regular expression language. Anything to improve the documentation will surely help.

**Comment by ryanscholzdvm** [comment]
This topic probably needs more discussion. We currently have 124 and 484 tag prefixes listed as acceptable in both the AIN and the MfrRFIDType RegEx. They are probably not appropriate to have listed in the MfrRFIDType, but @rmunger point, if we are going to list those two additional prefixes in AIN, should we also be listing all of the other potential country prefixes? The other option if we want to keep that AIN RegEx cleaner, is to create an additional International AIN type that could be utilized for AIN ID that is not 840 prefix, but is still a valid AIN. You could either do this in a defined type with a RegEx, or as a type option within OtherOfficialID (which would probably make more sense as the potential list gets very long.)

**Comment by jconlon** [comment]
Would suggest we open two separate issues to address the doc problem and the new internationalRFID type.

**Comment by ryanscholzdvm** [comment]
This issue was split into two new issues to enable better tracking - #78 will address the correction of the MfrRFID tag type documentation, while #79 will address the creation of a new international AID tag type.

**Comment by SusanCulpDVM** [comment]
Included in Release Version 3.0 Update.  Discussed with eCVI Workgroup on January 24, 2024.  All agreed to resolve and close this issue.
