### ISSUE TITLE
Ongoing Species List Refinement

### ISSUE THREAD

**Issue by mkm1879** [AAVLD-USAHA-ITStandards/eCVI#8]
Continuing from previous version, there is concern that the enumerated list of species is both too long and too incomplete.  The solution seems to be to find a way to implement "OTHER" in a way that does not involve all the analytical problems that arise from use of "OTHER".  

On the 2/8/18 call it was suggested to require text to accompany any use of the OTH code.  That was amended to also allow Text for the other codes.  This would lead to a three step coding process.
1. Find exact code...done.
2. Find a correct but non-specific code (POU poultry for Pigeon)...code to non-specific code and add text for more precision.
3. Find no correct code...code as OTH and add text for the species.

Implementing this required moving the species code from an attribute to a choice of two elements tentatively names "SpeciesCode" or "SpeciesOther".  Each has two attributes.  In Code the code is required and the text optional.  In Other the code is fixed as "OTH" and the text is required.

This suggested implementation is in the 2/8/18 draft of the schema.

**Comment by KimberlyTsao-USDA** [comment]
"Too long and too incomplete" seem to be fundamentally different problems in this case. Too incomplete is more problematic from a data standpoint - the more information left to free text entry, the less of that information will be realistically usable. Too long seems like more of an interface problem - lists of LOINC and SNOMED codes are also long. I'm sure there's a long and sordid history I'm not privy to, but why couldn't species be assigned OIDs that can be as general or specific as is appropriate?

**Comment by mkm1879** [comment]
From Justin Smith

All

I have been contemplating the recent group discussion concerning the species/class listing and “imported for the purpose of” choices.  I realize that we need to keep to a proven taxonomy structure as much as possible but I also wonder if we need to keep in mind that the eCVI data exchange standards are intended to exchange the needed information for the lot of animals moving.  I would venture that most state animal health officials would say a description of the animals involved and a concise purpose of movement gives them the needed information to determine if the animals are meeting entry requirements and what risks they might impose.

Although not completely encompassing, below is an example offered by  fellow SAHO’s that I can see meets what I would need to know for an informed decision of what might be required.  This is an example and would welcome your comments and critiques.

Species/Class
 
Equine
Beef cattle
Dairy cattle
Rodeo cattle
Sheep
Goats
Commercial swine
Transitional swine
Avian
Cervids
Camelids
Semen/embryos
Aquaculture
Dogs & cats
Exotics: _________________
Other:   _________________

**Comment by mkm1879** [comment]
On behalf of Alex Turner

Justin,
I think that is a great list. Thinking through what I see everyday from CVIs I think this would cover most things. The only questions I have would be:
•	Separate out Bison? I think that they come in "Other" currently. Maybe same question for a much smaller number of water buffalo? Both are Bovinae subfamily from a taxonomy standpoint.
•	Add "Recreational" to Purpose?
•	Omit "Direct to Slaughter" as this movement rarely requires a CVI, and as such we don't see a lot of these CVIs. If the movement required a CVI, it would be "Feeding to Slaughter"

**Comment by mkm1879** [comment]
Bison is in the list now.  Any other modifications needed?

**Comment by mkm1879** [comment]
This will be discussed on the next call.  If no additional problems are raised, we will vote to close.

**Comment by mkm1879** [comment]
New issue for material that travel with CVIs that are not live animals (semen, eggs, etc.)  Should be new Issue?

**Comment by StaceySchwabenlander** [comment]
I support the addition of 'Bison' to the list. In MN, we treat bison the same as cattle but would appreciate them being distinct in the species list.

Additionally, I find having the option of 'Semen/embryos' to be a useful addition and am happy to see that in Dr. Smith's list. We do not have a requirement for CVIs for semen, however, we receive a significant number of semen CVIs. We are finding that one vendor is used by veterinarians to issue the bulk of these eCVIs. In their eCVI, the species is typically listed as 'other' or 'swine' and semen is listed in various inappropriate fields such as the remarks field, the animal name field, official ID type, gender, breed, color, etc. Sometimes the number in shipment is listed as 1 head and the remarks or similar field will note the number of doses; other times the number in shipment will list the number of doses.
- Why is this an issue? Because is requires human eyes to figure out what the CVI represents. If the purpose of this schema is to assist in automated data flow, we need the species of 'semen/embryos' to be an option so that the 'number in shipment' field can be used to note the number of doses. This would allow our data systems to accurately pull this data and would no longer require personnel to correct all the invalid eCVIs we receive. If you are wondering why we need to correct these eCVIs, it is because if we do not want to document all these semen doses as actual swine imported/exported from our state.
- As an example, we have received 676 CVIs for swine semen in 2020 so far (this number represents CVIs from all sources except VSPS which doesn't send to our system). 600 of these were eCVIs that required my staff to correct them, otherwise all of our reporting would inaccurately inflate swine imports/exports.
- I realize no one has suggested we not have this option, but I thought it may be helpful to outline support for the option.

One question - as presented above in Dr. Smith's list, are dogs and cats listed together or distinctly? As a state that has commercial breeding rules for dogs and cats, I think we would prefer dogs and cats to be listed as distinct species.

**Comment by StaceySchwabenlander** [comment]
Sorry @mkm1879 - it took me too long to write and submit my post, I didn't see your comment until now. If the group prefers a different issue be made to address non live animal CVIs, I'm happy to move the appropriate comments to that new issue.

**Comment by SusanCulp** [comment]
@mkm1879 , I do think this should be a new issue (material that travel with CVIs that are not live animals (semen, eggs, etc.).  She we wait until we meet again on May 14th to discuss or separate it out now?

**Comment by SusanCulp** [comment]
@StaceySchwabenlander dogs and cats are listed distinctly.  

From an old "eCVI Version 2 Standard Contents" doc I downloaded a few months ago:

SpeciesCode
For animals with official species codes, the code is required with optional text to add detail if necessary. 
Attributes
•	Code: Required
SpeciesCodes
A subset of USDA species codes to support the most common eCVI usages. All other species can be sent as SpeciesOther which is not enumerated. 
Values: 
o	AQU ( Aquaculture) 
o	BEF ( Beef) 
o	BIS ( Bison) 
o	BOV ( Bovine (Bison and Cattle) DEPRECATED) 
o	CAM ( Camelid (Alpacas, Llamas, etc.)) 
o	CAN ( Canine) 
o	CAP ( Caprine (Goats)) 
o	CER ( Cervids) 
o	CHI ( Chickens) 
o	DAI ( Dairy) 
o	EQU ( Equine (Horses, Mules, Donkeys, Burros)) 
o	FEL ( Feline) 
o	OVI ( Ovine (Sheep)) 
o	POR ( Porcine (Swine)) 
o	TUR ( Turkeys) 
•	Text: Optional 
SpeciesOther
The species coded in the standard include only those commonly needed for regulatory action related to the movement. Many other official species codes can be found at http://???? Because not all systems may understand these other codes, human readable Text is required in addition to the code. For animals without an official species code, the code may be omitted the default value is OTH and text used to define the actual taxonomy is required. 
Attributes
•	Code: Optional 
•	Text: Required

**Comment by mkm1879** [comment]
Yes, the compromise the committee tried to reach was to have all the most common species explicitly called out on the assumption that it was reasonable to ask ALL receiving systems to "understand" these.  Because many of us have other species that are locally important, the coded "SpeciesOther" was created.  The two important ones here are PGN and QUA but other places have other important unusual species.

**Comment by mkm1879** [comment]
We have noticed dairy goats showing up coded with species [sic] code "DAI".  I had assumed that meant dairy cattle but the documentation just says " Dairy".

Change DAI and BEF to specify cattle?

This is why terminologists hate mixing variables like this.

**Comment by StaceySchwabenlander** [comment]
I would agree with @mkm1879 that the schema should clearly indicate that DAI and BEF codes are for cattle only.
